### ISSUE TITLE
reordering logic: dragOver vs dragEnd

### ISSUE THREAD

**Issue by drzraf** [siffogh/drag-and-drop-article#1]
It's not clear why reordering happens during dragOver instead of dragEnd.

**Comment by sukrut-gs** [comment]
I can take this up.

**Comment by sukrut-gs** [comment]
Fixed in this PR
https://github.com/siffogh/drag-and-drop-article/pull/2

**Comment by siffogh** [comment]
Thanks @drzraf  for taking the time to write an issue and @sukrut-gs for pushing a potential fix.
The reason for the reordering happening in `onDragOver` is because we want to show a preview how the list will look like whenever we move the dragged element over another.

If you look again at the gif showing the final result, you'd see that the list changes whenever you drag an element over another before even dropping it.

Does that make sense?
